path_fastqs=/home/vinzenz/development/LRSV-detection/development/test/ont-r10/mcr_reads
path_bam=/home/vinzenz/development/LRSV-detection/development/test/ont-r10/minimap2.ont-r10.10x.chr22.bam
path_bambai=/home/vinzenz/development/LRSV-detection/development/test/ont-r10/minimap2.ont-r10.10x.chr22.bam.bai
path_crs=/home/vinzenz/development/LRSV-detection/development/test/ont-r10/minimap2.ont-r10.10x.chr22.crs
path_filtered_rafs=/home/vinzenz/development/LRSV-detection/development/test/ont-r10/minimap2.ont-r10.10x.chr22.filtered.raf
path_mcrs=/home/vinzenz/development/LRSV-detection/development/test/ont-r10/minimap2.ont-r10.10x.chr22.mcrs
path_raf=/home/vinzenz/development/LRSV-detection/development/test/ont-r10/minimap2.ont-r10.10x.chr22.raf
path_ras/home/vinzenz/development/LRSV-detection/development/test/ont-r10/minimap2.ont-r10.10x.chr22.ras
path_signal=/home/vinzenz/development/LRSV-detection/development/test/ont-r10/minimap2.ont-r10.10x.chr22.signal
path_wig/home/vinzenz/development/LRSV-detection/development/test/ont-r10/minimap2.ont-r10.10x.chr22.wig
path_wigtdf/home/vinzenz/development/LRSV-detection/development/test/ont-r10/minimap2.ont-r10.10x.chr22.wig.tdf
path_reads=/home/vinzenz/development/LRSV-detection/development/test/ont-r10/ont-r10.10x.reads.crs.chr22.fastq
path_QC=/home/vinzenz/development/LRSV-detection/development/test/ont-r10/QC
