#!/usr/bin/env python3
"""
This script reads an SVpatterns database and writes all SVpatterns to BED intervals.

The BED file contains four columns: chr, start, end, type:size
For INV-DEL or INV-DUP types, the outer intervals are used.
"""

import argparse
import logging
from pathlib import Path

from ..localassembly import SVpatterns

log = logging.getLogger(__name__)


def svpatterns_to_bed(input_db: Path, output_bed: Path) -> None:
    """
    Read SVpatterns from database and write them to a BED file.

    Args:
        input_db: Path to the SVpatterns database file
        output_bed: Path to the output BED file
    """
    log.info(f"Reading SVpatterns from {input_db}")

    # Read all SVpatterns from the database
    svpatterns_list = SVpatterns.read_svPatterns_from_db(database=input_db)

    log.info(f"Found {len(svpatterns_list)} SVpatterns")

    # Write to BED file
    with open(output_bed, "w") as bed_out:
        for svpattern in svpatterns_list:
            sv_type = svpattern.get_sv_type()
            size = svpattern.get_size()

            # For INV-DEL and INV-DUP, use outer intervals
            if isinstance(
                svpattern,
                (
                    SVpatterns.SVpatternInversionDeletion,
                    SVpatterns.SVpatternInversionDuplication,
                ),
            ):
                chr_name, start, end = svpattern.get_reference_region(inner=False)
            else:
                chr_name, start, end = svpattern.get_reference_region()

            # Create the type:size field
            type_size_field = f"{sv_type}:{size}"

            # Write BED line: chr, start, end, type:size
            bed_out.write(f"{chr_name}\t{start}\t{end}\t{type_size_field}\n")

    log.info(f"Wrote {len(svpatterns_list)} SVpatterns to {output_bed}")


def get_parser() -> argparse.ArgumentParser:
    """Create argument parser for the script."""
    parser = argparse.ArgumentParser(
        description="Convert SVpatterns database to BED file",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    parser.add_argument(
        "-i",
        "--input",
        type=Path,
        required=True,
        help="Input database file with SVpatterns (generated by consensus_align)",
        metavar="DB",
    )

    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        required=True,
        help="Output BED file",
        metavar="BED",
    )

    parser.add_argument(
        "-v", "--verbose", action="store_true", help="Enable verbose logging"
    )

    return parser


def main():
    """Main entry point for the script."""
    parser = get_parser()
    args = parser.parse_args()

    # Setup logging
    log_level = logging.DEBUG if args.verbose else logging.INFO
    logging.basicConfig(
        level=log_level, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    )

    # Validate input file exists
    if not args.input.exists():
        log.error(f"Input database file not found: {args.input}")
        return 1

    # Convert SVpatterns to BED
    try:
        svpatterns_to_bed(args.input, args.output)
        log.info("Conversion completed successfully")
        return 0
    except Exception as e:
        log.error(f"Error during conversion: {e}", exc_info=True)
        return 1


if __name__ == "__main__":
    exit(main())
